version: '2'
services:
    db:
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: root
            MYSQL_PASSWORD: root

    web:
        volumes:
            - "./src:/var/www/html"
        depends_on:
            - db
        image: php:7.1-apache
        links:
            - db
        ports:
            - "8001:80"


